-- ArenaHub - schema atual para PostgreSQL/NeonDB (equivale a: alembic upgrade head -> 0002_frontend_contract)
-- Use em um banco VAZIO. O caminho recomendado é o Alembic (cd Backend && alembic upgrade head).
-- Se aplicar este arquivo manualmente, depois rode:  alembic stamp head

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    senha_hash VARCHAR NOT NULL,
    role VARCHAR NOT NULL DEFAULT 'jogador',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_users_id ON users (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS teams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL UNIQUE,
    tag VARCHAR(8) NOT NULL DEFAULT '',
    cor VARCHAR(16) NOT NULL DEFAULT '#00f0ff',
    capitao VARCHAR NOT NULL DEFAULT '',          -- nick do capitão
    jogadores JSON NOT NULL DEFAULT '[]',         -- lista de nicks
    capitao_id INTEGER REFERENCES users(id),      -- usuário que cadastrou a equipe
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_teams_id ON teams (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_teams_nome ON teams (nome);

CREATE TABLE IF NOT EXISTS tournaments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL,
    jogo VARCHAR NOT NULL DEFAULT 'Outro',
    formato VARCHAR NOT NULL DEFAULT 'pontos_corridos',
    descricao VARCHAR,
    status VARCHAR NOT NULL DEFAULT 'INSCRICOES_ABERTAS',
    data_inicio TIMESTAMP,                        -- UTC
    data_fim TIMESTAMP,                           -- UTC
    max_equipes INTEGER NOT NULL DEFAULT 8,
    premiacao VARCHAR,
    organizador_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tournaments_formato CHECK (formato IN ('pontos_corridos', 'eliminatoria')),
    CONSTRAINT ck_tournaments_status CHECK (status IN ('INSCRICOES_ABERTAS', 'EM_ANDAMENTO', 'FINALIZADO')),
    CONSTRAINT ck_tournaments_max_equipes CHECK (max_equipes >= 2)
);

CREATE INDEX IF NOT EXISTS ix_tournaments_id ON tournaments (id);

-- Equipes inscritas em cada campeonato (N:N)
CREATE TABLE IF NOT EXISTS tournament_teams (
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    PRIMARY KEY (tournament_id, team_id)
);

CREATE INDEX IF NOT EXISTS ix_tournament_teams_team_id ON tournament_teams (team_id);

CREATE TABLE IF NOT EXISTS matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER REFERENCES tournaments(id),
    rodada INTEGER NOT NULL DEFAULT 1,
    team_a_id INTEGER REFERENCES teams(id),
    team_b_id INTEGER REFERENCES teams(id),       -- NULL = bye (avança sem adversário)
    score_a INTEGER DEFAULT 0,
    score_b INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'AGENDADO',            -- AGENDADO | EM_ANDAMENTO | FINALIZADO
    data_hora TIMESTAMP,                          -- UTC
    CONSTRAINT ck_matches_rodada CHECK (rodada >= 1)
);

CREATE INDEX IF NOT EXISTS ix_matches_id ON matches (id);
CREATE INDEX IF NOT EXISTS ix_matches_tournament_id_rodada ON matches (tournament_id, rodada);
