-- ArenaHub - schema inicial para PostgreSQL/NeonDB
-- Execute este arquivo uma vez em um banco vazio.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    senha_hash VARCHAR NOT NULL,
    role VARCHAR NOT NULL DEFAULT 'jogador',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_users_id ON users (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS teams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL UNIQUE,
    capitao_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_teams_id ON teams (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_teams_nome ON teams (nome);

CREATE TABLE IF NOT EXISTS tournaments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL,
    descricao VARCHAR,
    organizador_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_tournaments_id ON tournaments (id);

CREATE TABLE IF NOT EXISTS matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER REFERENCES tournaments(id),
    team_a_id INTEGER REFERENCES teams(id),
    team_b_id INTEGER REFERENCES teams(id),
    score_a INTEGER DEFAULT 0,
    score_b INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'AGENDADO',
    data_hora TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_matches_id ON matches (id);
